# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE are ignored when building from the command line, check
# build.gradle files instead.

# When configured, Gradle will run in offline mode and will not download any dependencies from the internet.
# org.gradle.offline=true

# AndroidX package structure to make it easier to support multiple build types
# feel free to modify your sourceSets block to remove * note if you have issues
# uncomment for Full Java compatibility mode (not recommended for new projects). Requires JDK 11 or greater.
# org.gradle.jvmargs=-Xmx1536m -Dfile.encoding=UTF-8 -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+ParallelRefProcEnabled -XX:G1NewCollectionHeuristicPercent=30 -XX:G1ReservePercent=20

# Enables namespacing of each library's R class so that its R class includes only the
# resources declared in the library itself and does not include a namespace for resources
# declared in the library's dependencies. Disabling this is useful for Gradle subprojects
# where it is difficult to work with internal implementation details of interdependencies.
android.nonTransitiveRClass=true
android.useAndroidX=true
android.enableJetifier=true
kotlin.code.style=official
